#ifndef AIXA_SRC_MAINLIB_GUI_BITMAP_PROCEDURALPROVIDER_H
#define AIXA_SRC_MAINLIB_GUI_BITMAP_PROCEDURALPROVIDER_H

#include "Bitmap.h"

class ProceduralProvider {
public:

    Bitmap buildBitmap();
};


#endif //AIXA_SRC_MAINLIB_GUI_BITMAP_PROCEDURALPROVIDER_H
