function(build_sources_list SRCS)
    file(GLOB_RECURSE  SOURCEFILES CONFIGURE_DEPENDS *.cpp *.h *.cu *.cuh *.hpp *.ui *.qrc *.rc)
    #traverse unit test files and remove from sources
    file(GLOB_RECURSE SRCS_UTEST CONFIGURE_DEPENDS  *_UTest.* )
    if(SRCS_UTEST)
        list(REMOVE_ITEM SOURCEFILES ${SRCS_UTEST})
    endif()
    set (SRCS ${SOURCEFILES} PARENT_SCOPE)
endfunction()

function(dump_cmake_variables)
    get_cmake_property(_variableNames VARIABLES)
    list (SORT _variableNames)
    foreach (_variableName ${_variableNames})
        if (ARGV0)
            unset(MATCHED)
            string(REGEX MATCH ${ARGV0} MATCHED ${_variableName})
            if (NOT MATCHED)
                continue()
            endif()
        endif()
        message(STATUS "${_variableName}=${${_variableName}}")
    endforeach()
endfunction()